"""Build the Mining Simulation web page from the planner's standalone simulator.html.

The simulator is developed as one self-contained HTML file. This turns that file into
www/mining_simulation.html without changing her code: the page keeps its markup, its
<style id="app-style"> and its <script id="app-main"> inline (the Share feature copies
them from the live page), the three CDN libraries are served from this app, and the
Frappe storage adapter is loaded after her script so projects are kept in
Mining Simulation Project documents. In <head>, after her styles, the Frappe theme
(frappe_theme.css / .js) maps her design tokens onto the user's Frappe theme.

Run it whenever a new simulator.html arrives:

    bench --site <site> execute is_production.geo_planning.mining_simulation_sync.sync \
        --kwargs "{'source': '/path/to/simulator.html'}"

or without a site: python apps/is_production/is_production/geo_planning/mining_simulation_sync.py simulator.html
"""

import os
import sys

APP_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(APP_DIR, "www", "mining_simulation.html")

# The CDN tags in simulator.html and the local copy that replaces each (public/mining_simulation/vendor)
LIBRARIES = [
	('<script src="https://cdn.jsdelivr.net/npm/three@0.147.0/build/three.min.js"></script>', "three.min.js"),
	(
		'<script src="https://cdn.jsdelivr.net/npm/three@0.147.0/examples/js/controls/OrbitControls.js"></script>',
		"OrbitControls.js",
	),
	('<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>', "xlsx.full.min.js"),
]
ASSET_URL = "/assets/is_production/mining_simulation/"

NOTICE = (
	"<!-- Generated by is_production/geo_planning/mining_simulation_sync.py from the planner's simulator.html. "
	"Do not edit by hand: change simulator.html and run the sync again. -->\n"
)


def raw(text):
	"""Jinja must not interpret the simulator's own code."""
	if "{% endraw %}" in text:
		raise ValueError("simulator.html contains '{% endraw %}' and cannot be wrapped for Jinja")
	return "{% raw %}" + text + "{% endraw %}"


def build(html):
	# her script tags that load the libraries: all three, adjacent, before <script id="app-main">
	positions = []
	for tag, _ in LIBRARIES:
		i = html.find(tag)
		if i < 0:
			raise ValueError(f"Library tag not found in simulator.html: {tag}")
		positions.append(i)
	main = html.find('<script id="app-main">')
	if main < 0:
		raise ValueError('<script id="app-main"> not found in simulator.html')
	start, end = min(positions), max(positions) + len(LIBRARIES[positions.index(max(positions))][0])
	if not (start < end <= main) or html[start:end].count("<script") != len(LIBRARIES):
		raise ValueError("The library tags are expected together, just before the app script")

	body_end = html.rfind("</body>")  # the last one: her code also contains '</body>' inside strings
	if body_end < main:
		raise ValueError("</body> not found after the app script")
	head_end = html.find("</head>")
	if not 0 < head_end < start:
		raise ValueError("</head> not found before the library tags")

	head = html[:head_end].replace("<head>\n", "<head>\n" + NOTICE, 1)
	theme_part = (
		"<script>window.MINING_SIM = {{ mining_sim | tojson }};</script>\n"
		f'<link rel="stylesheet" href="{ASSET_URL}frappe_theme.css?v={{{{ asset_version }}}}">\n'
		f'<script src="{ASSET_URL}frappe_theme.js?v={{{{ asset_version }}}}"></script>\n'
	)
	libs = "\n".join(f'<script src="{ASSET_URL}vendor/{name}?v={{{{ asset_version }}}}"></script>' for _, name in LIBRARIES)
	frappe_part = f'<script src="{ASSET_URL}frappe_store.js?v={{{{ asset_version }}}}"></script>\n'
	return (
		raw(head)
		+ theme_part
		+ raw(html[head_end:start])
		+ libs
		+ raw(html[end:body_end])
		+ frappe_part
		+ raw(html[body_end:])
	)


def sync(source):
	with open(source, encoding="utf-8") as f:
		html = f.read()
	out = build(html)
	with open(TARGET, "w", encoding="utf-8") as f:
		f.write(out)
	print(f"Wrote {TARGET} ({len(out):,} characters) from {source}")
	return TARGET


if __name__ == "__main__":
	if len(sys.argv) != 2:
		sys.exit("usage: mining_simulation_sync.py path/to/simulator.html")
	sync(sys.argv[1])
